import Benefits from '@/components/screens/home/Benefits/Benefits'
import Offer from '@/components/screens/home/Offer/Offer'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Shape</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Offer/>
      <Benefits/>
    </>
  )
}
